### ISSUE TITLE
Should import_upstrem.sh be imported ?

### ISSUE THREAD

**Issue by CoXier** [Piasy/VideoCRE#1]
In the script, it seems to be used to copy core files of another **local** project into current project.But is it necessary to import this script into current project?

**Comment by Piasy** [comment]
Yes it is, but I do want to keep it under source control, so... :)

**Comment by CoXier** [comment]
I think you can ignore this file using .gitignore.

**Comment by Piasy** [comment]
As I said, I **do want to keep it under source control**.
