### ISSUE TITLE
store images like video 

### ISSUE THREAD

**Issue by shishram** [Piasy/VideoCRE#3]
How can we extract direct images from stream? any references or solution?

**Comment by Piasy** [comment]
I think [this](https://github.com/Piasy/VideoCRE/blob/master/VideoCRE/src/main/java/org/webrtc/SurfaceViewRenderer.java#L122) is what you want, but I haven't use this feature. Try it out yourself :)

**Comment by shishram** [comment]
public void addFrameListener(
      EglRenderer.FrameListener listener, float scale, RendererCommon.GlDrawer drawerParam) {
    eglRenderer.addFrameListener(listener, scale, drawerParam);
  }

Where to call this and what will be listener, scale and drawerParam?

**Comment by Piasy** [comment]
I don't know neither, you can RTFSC :)
