### ISSUE TITLE
请教下接入滤镜问题

### ISSUE THREAD

**Issue by jtyang** [Piasy/VideoCRE#4]
Piasy，你好，请问下是否有研究过webrtc视频采集模块如何接入类似GPUImage的滤镜效果呢？Thanks！

**Comment by Piasy** [comment]
抱歉，这块没有深入研究过，不过应该可以在获取相机数据的地方做图像预处理，然后再把数据送到 native 层，进而预览、编码发送。

**Comment by jtyang** [comment]
嗯嗯，Thanks！
