### ISSUE TITLE
您好，请教个摄像头翻转的问题

### ISSUE THREAD

**Issue by jtyang** [Piasy/VideoCRE#5]
许兄，请教下Camera1Session在采集完后，我看你加了一个矩阵处理matrixHelper.flip(transformMatrix, true, true);这里想请教下：
1）为何这里不用区分前后摄像头呢？（看rtc的源码是只有前摄像头的时候才乘以一个水平翻转矩阵）
2）一般前置摄像头，预览的时候需要看到自己的镜像，而给编码器的时候一般是需要水平翻转下。不知许兄是否有研究过webrtc是在哪个地方实现前摄像头数据给编码时做的水平翻转处理呢？跟了半天的源码都没发现它是在哪做的水平翻转处理。

多谢！

**Comment by Piasy** [comment]
WebRTC 的处理应该都是在 native 层做的，native 的这部分代码，我没有深入研读过。

至于为什么没有区分前后置，是因为我发现旋转+水平翻转+垂直翻转，都好使。WebRTC 里 GL 绘制的代码和 Grafika 里如出一辙，而 Grafika 里的代码以前我们项目中就是这么干的，已经经过很多客户验证没问题了。
